// This file is responsible for handling (blog) posts build logic.
import * as fs from 'node:fs';
import * as path from 'node:path';
import showdown from 'showdown';

import * as constants from './constants';
import * as iface from './iface';
import * as boms from './boms';
import * as buildSlideshows from './build-slideshows';
import * as threedSlideshows from './3d-slideshows';
import * as playlists from './playlists';
import * as imageSrcsets from './image-srcsets';

// This showdown markdown extension:
// * Changes (text) to <parenthentical>(text)</parenthetical> for styling purposes
// * Force all links declared in markdown to open in new tab
// * Add ondblclick='this.requestFullscreen()' to all images declared in markdown
// Notes:
// lang: language extension to add new Markdown syntax to Showdown
// output: output extension (or modifier) to alter the HTML output generated by Showdown
// If a filter functon is present, both regex and replace properties will be ignored.
const parentheticalFormatter = {
  type: 'output',
  filter: (text: string) => {
    console.debug('showdown meblog-markdown-formatter: format parenthetical', text);

    text = text.replace(/\(([^)]+)\)/gi, (match, text, rest) => {
      // This is bound to break: ondblclick='this.requestFullscreen()' gets matched,
      //  and I'm certain there will be other edge cases to account for.
      if (match === '()') { return match; }

      console.debug('parenthetical match', match, 'text', text, 'rest', rest);

      return `<parenthetical>(${text})</parenthetical>`;
    });

    return text;
  }
};

const linkFormatter = {
  type: 'output',
  filter: (text: string) => {
    console.debug('showdown meblog-markdown-formatter: format link', text);

    text = text.replace(/<a\s+(?:[^>]*?\s+)?href=["']([^"']*)["']([^>]*)>/gi, (match, text, rest) => {
      console.debug('match', match, 'text', text, 'rest', rest);

      if (match.includes('target="_blank"') || match.includes("target='_blank'") || text.startsWith('#')) {
        return match;
      }

      return `<a href='${text}' target='_blank'${rest}>`;
    });

    return text;
  }
};

// FIXME This is most certainly broken, and that might be ok - the build slideshows go black when double-clicked,
//  probably due to some weird shit you're doing to make them work.
const imageFormatter = {
  type: 'output',
  filter: (text: string) => {
    console.debug('showdown meblog-markdown-formatter: format image', text);

    text = text.replace(/<image[^>]+>/gi, (match, text, rest) => {
      console.debug('match', match, 'text', text, 'rest', rest);

      if (match.includes('ondblclick=')) { return match; }

      return match.replace(/>$/, " ondblclick='this.requestFullscreen()'>");
    });

    // You mostly use <image> tags but hell who knows what I'm smoking some days.
    text = text.replace(/<img[^>]+>/gi, (match, text, rest) => {
      console.debug('match', match, 'text', text, 'rest', rest);

      if (match.includes('ondblclick=')) { return match; }

      return match.replace(/>$/, " ondblclick='this.requestFullscreen()'>");
    });

    return text;
  }
};

const markdownConverter = new showdown.Converter({
  headerLevelStart: 5,
  extensions: [parentheticalFormatter, linkFormatter, imageFormatter]
});

export const getAll = async (weWant: iface.TPostFilter, postType: iface.TPostType) => {
  console.trace('getAll (posts)', postType, weWant);

  const posts: Array<iface.IPost> = [];

  await findAndParsePosts(constants.postsDir, posts, postType, weWant);

  return posts;
};

const findAndParsePosts = async (dir: string, posts: Array<iface.IPost>, postType: iface.TPostType, weWant: iface.TPostFilter) => {
  console.trace('findAndParsePosts', dir, postType);

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const childPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      await findAndParsePosts(childPath, posts, postType, weWant);
    }

    if (!entry.isDirectory() && path.extname(childPath) === constants.postExtension) {
      const template = fs.readFileSync(childPath).toString();
      const [rawPostInfo, postInfo] = getPostInfo(template);

      // You do a bunch of filtering here.
      // For the dev publish stage, you want to show all posts, including drafts.
      // For the prod publish stage, you only want to show published posts (and their corresponding info).
      if (postInfo.type !== postType) {
        console.warn('ignoring post, postInfo.type !== postType', postInfo.type, postType);

        continue;
      }

      if (weWant === 'published' && postInfo.draft) {
        console.warn('ignoring post, weWant published but got draft');

        continue;
      }

      if (weWant === 'draft' && !postInfo.draft) {
        console.warn('ignoring post, weWant draft but got published');

        continue;
      }

      if (!postInfo.title) { postInfo.title = entry.name.replace(constants.postExtension, ''); } // Derive title from file name.
      console.debug('postInfo', childPath, postInfo);

      let html = markdownConverter.makeHtml(template);

      // You could make these Markdown extensions but that seems like overkill.
      // Instead just replace the post's HTML in a more ad-hoc manner.
      //
      // Generates boms, build slideshows, and playlist HTML/JavaScript,
      //  then inserts respective data into each post's HTML.
      html = html.replace(rawPostInfo, ''); // Remove this because otherwise when you try to substitute boms and build slideshows it will interfere.

      const bomReferences: iface.IBOMMarkdownReference[] = [];
      const buildSlideshowReferences: iface.ISlideshowMarkdownReference[] = [];
      const threedSlideshowReferences: iface.ISlideshowMarkdownReference[] = [];
      let playlist: iface.IPlaylistMarkdownReference | undefined;

      let totalCostUSDAllBoms = 0;
      if (postInfo.boms) {
        console.debug('found boms', postInfo.boms);

        for (const bom of postInfo.boms) {
          // Ignore boms you're using as a notepad.
          const wipBomFile = path.join(process.cwd(), `src/frontend/boms/posts/${bom.name}.wip`);
          console.debug('wipBomFile', wipBomFile);

          if (fs.existsSync(wipBomFile)) {
            console.warn('skipping bom, wip', bom.name);

            continue;
          }

          const [bomHtml, totalCostUSD] = await boms.generateHTML(postInfo, bom);
          totalCostUSDAllBoms = totalCostUSDAllBoms + totalCostUSD;

          console.debug('bom html', bomHtml);

          console.debug(`replacing bom.templateKey ${bom.templateKey} in post html`, html.includes(bom.templateKey));
          html = html.replace(`<p>${bom.templateKey}</p>`, bomHtml); // Wrap in <p> because you converted from Markdown without using a Showdown extension.

          bomReferences.push({ ...bom, html: bomHtml });
        }
      }

      if (postInfo.buildSlideshows) {
        console.debug('found build slideshows', postInfo.buildSlideshows);

        for (const buildSlideshow of postInfo.buildSlideshows) {
          const buildSlideshowHtml = await buildSlideshows.generateHTML(postInfo, buildSlideshow);
          console.debug('build slideshow html', buildSlideshowHtml);

          console.debug(`replacing buildSlideshow.templateKey ${buildSlideshow.templateKey} in post html`, html.includes(buildSlideshow.templateKey));
          html = html.replace(`<p>${buildSlideshow.templateKey}</p>`, buildSlideshowHtml); // Wrap in <p> because you converted from Markdown without using a Showdown extension.

          buildSlideshowReferences.push({ ...buildSlideshow, html: buildSlideshowHtml });
        }
      }

      if (postInfo.threedSlideshows) {
        console.debug('found 3d slideshows', postInfo.threedSlideshows);

        for (const threedSlideshow of postInfo.threedSlideshows) {
          const threedSlideshowHtml = await threedSlideshows.generateHTML(postInfo, threedSlideshow);
          console.debug('3d slideshow html', threedSlideshowHtml);

          console.debug(`replacing threedSlideshow.templateKey ${threedSlideshow.templateKey} in post html`, html.includes(threedSlideshow.templateKey));
          html = html.replace(`<p>${threedSlideshow.templateKey}</p>`, threedSlideshowHtml); // Wrap in <p> because you converted from Markdown without using a Showdown extension.

          threedSlideshowReferences.push({ ...threedSlideshow, html: threedSlideshowHtml });
        }
      }

      if (postInfo.playlist) {
        console.debug('found playlist', postInfo.playlist);

        const playlistHtml = await playlists.generateHTML(postInfo.playlist);
        console.debug('playlist html', playlistHtml);

        // The template key is always "playlist".
        // The Markdown file should have {playlist} text somewhere.
        console.debug(`replacing playlist templateKey {playlist} in post html`, html.includes('{playlist}'));
        html = html.replace(`<p>{playlist}</p>`, playlistHtml); // Wrap in <p> because you converted from Markdown without using a Showdown extension.

        playlist = postInfo.playlist;
      }

      // Convert <image>/<img> tags to use imgsrcsets and generate the images from the single full-res image.
      // Generate variants are written to <meblog-src>/src/frontend/public/images/srcsets/<postInfo.resourceDirName>/.
      html = await imageSrcsets.generateImagesForPostAndModifyPostHtml(html, postInfo.resourceDirName ?? postInfo.title.toLowerCase().replaceAll(' ', '-'));

      posts.push({
        postInfo,
        html,
        boms: bomReferences,
        buildSlideshows: buildSlideshowReferences,
        threedSlideshows: threedSlideshowReferences,
        totalCostUSDAllBoms,
        playlist
      });
    }
  }
};

const getPostInfo = (template: string): [string, iface.IPostInfo] => {
  const postInfo = template.match(/<!--[\s\S]*?-->/g);

  console.trace('getPostInfo', template, postInfo || 'n/a');

  if (postInfo && postInfo[0]) {
    let postInfoString = postInfo[0];

    postInfoString = postInfoString.replace('<!--', '');
    postInfoString = postInfoString.replace('-->', '');
    postInfoString = postInfoString.replace('\n', '');
    postInfoString = postInfoString.trim();

    console.debug('postInfoString', postInfoString);

    return [postInfo[0], JSON.parse(postInfoString) as iface.IPostInfo];
  }

  throw new Error('Post info not parseable');
}

export const getAllDrafts = async (postType: iface.TPostType) => {
  console.trace('getAllDrafts (posts)', postType);

  const posts: Array<iface.IPost> = [];

  await findAndParsePosts(constants.postsDir, posts, postType, 'draft');

  return posts;
};
